---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ['rmq.local:15692']


remote_write:
  - url: "http://grafana.local:3000"
