---
minimum_pre_commit_version: "2.9.2"

default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.950"
    hooks:
      - id: mypy
        additional_dependencies: [types-redis==4.2.5, types-requests==2.27.27, types-retry==0.9.7, types-freezegun==1.1.9]

  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        additional_dependencies: [".[toml]"]
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.26.3"
    hooks:
      - id: yamllint

  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
