---
version: "3.9"

services:
  test.neo4j.local:
    image: neo4j:4.4.7-community
    environment:
      - NEO4J_AUTH=neo4j/wikicrawl

  test.redis.local:
    image: "redis:alpine"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: tests
    command: ['/bin/ash', '-c', "/home/wikicrawl/wait && python -m pytest"]
    environment:
      - DATABASE_USER=neo4j
      - DATABASE_PASSWORD=wikicrawl
      - DATABASE_URL=bolt://test.neo4j.local
      - WAIT_HOSTS=test.neo4j.local:7687
      - WAIT_TIMEOUT=120
      - WAIT_SLEEP_INTERVAL=6
    depends_on:
      - test.neo4j.local
    volumes:
      - ./:/home/wikicrawl/dev

  build:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: build
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - ./:/home/wikicrawl/dev

  stub-data-generator:
    image: stub-data-generator:local
    build:
      context: .
      dockerfile: Dockerfile.stub
    environment:
      - REDIS_HOST=test.redis.local
      - STUB_OUTPUT_DIRECTORY=/home/wikicrawl/output
      - LOGGING_ENGINES=STREAM
      - WIKI_DOMAIN=https://en.wikipedia.org
      - CRAWL_SILENT_HTTP_STATUS_CODES=429
    depends_on:
      - test.redis.local
    volumes:
      - ./.stub:/home/wikicrawl/output
