[tool.isort]
line_length = 120
profile = "black"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.mypy]
python_version = "3.9"
pretty = true

[tool.bandit]
exclude_dirs = [
    "*/tests*/*",
]

[tool.pytest.ini_options]
addopts = "--cov=. --junitxml=./.tests/report.xml --durations=5"
asyncio_mode="auto"

[tool.coverage.run]
omit = [
    "*tests*"
]

[tool.coverage.report]
show_missing = true
