from environs import Env

env = Env()

CRAWL_DOWNLOAD_MAXIMUM_BATCH_SIZE: int = env.int("CRAWL_DOWNLOAD_MAXIMUM_BATCH_SIZE", 25)
CRAWL_SILENT_HTTP_STATUS_CODES: str = env("CRAWL_SILENT_HTTP_STATUS_CODES", "")
