---
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki.local:3100
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.local:9090
  - name: Neo4j
    type: kniepdennis-neo4j-datasource
    jsonData:
      url: neo4j://neo4j.local:7687
      database: ""
      username: "neo4j"
    secureJsonData:
      password: "wikicrawl"
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite.local:80
    jsonData:
      graphiteVersion: "1.1"
