---
name: Wikicrawl CI
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: chown
        run: sudo chown -R 5000:5000 ./
      - name: unit tests
        run: make ci UID=5000 GID=5000
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '.tests/report.xml'
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          verbose: true
