---
name: Wikicrawl CI
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: chown
        run: sudo chown -R 5000:5000 ./
      - name: unit tests
        run: make ci UID=5000 GID=5000
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '.tests/report.xml'
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Pyblisj Rest Report (2)            # Name of the check run wich will be created
          path: .tests/report.xml    # Path to test results
          reporter: java-junit        # Format of test results
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          verbose: true
