{
 "title": "WIKICRAWL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "level", "label": "Log level", "query": "label_values(level)" },
   { "name": "search", "label": "Search log" }
  ]
 },
 "panels": [
  { "title": "CRAWLING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PENDING TASK",
   "type": "timeseries",
   "description": "Number of tasks pending\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"crawling-queue\"}"
    }
   ]
  },
  {
   "title": "TASK COMPLETED / MINUTE",
   "type": "timeseries",
   "description": "Number of tasks completed\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A*10", "type": "math" },
    { "expression": "$C*10", "type": "math" }
   ]
  },
  {
   "title": "TASK DURATION",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.wikicrawl.workers.crawl.duration.mean"
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{level=~\"$level\", task=\"wikicrawl.workers.crawl\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "TOTAL LOGS",
   "type": "stat",
   "description": "Number of logs emitted (any level)\n",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "max", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  { "title": "RECORDING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "PENDING TASK",
   "type": "timeseries",
   "description": "Number of tasks pending\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"recording-queue\"}"
    }
   ]
  },
  {
   "title": "TASK COMPLETED / MINUTE",
   "type": "timeseries",
   "description": "Number of tasks completed\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A*10", "type": "math" },
    { "expression": "$C*10", "type": "math" }
   ]
  },
  {
   "title": "TASK DURATION",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.wikicrawl.workers.record.duration.mean"
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{level=~\"$level\", task=\"wikicrawl.workers.record\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "TOTAL LOGS",
   "type": "stat",
   "description": "Number of logs emitted (any level)\n",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "max", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "reduce" }
   ]
  },
  { "title": "DATABASE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "NODES",
   "type": "stat",
   "description": "Number of nodes\n",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "cypherQuery": "MATCH (n) return count(n)" }
   ]
  },
  {
   "title": "EDGES",
   "type": "stat",
   "description": "Number of edges\n",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cypherQuery": "MATCH ()-[r]->() RETURN count(r)"
    }
   ]
  }
 ]
}